### PR TITLE
#22 :  header_var with 'defined', not 'default'

### PR DESCRIPTION
**Pull request by hugobqd**
The default state doesn't work with default when empty, use twig's defined instead

### CODE REVIEW

**Comment by hugobqd** [comment]
OK, I see, I have modified the wrong variables assignments. Does the 'default' work fine for you?

**Comment by cweiske** [comment]
sorry, can't test right now.

**Comment by tribut** [comment]
Yes, both the logic (using `show_sidebar` for unrelated settings) and using `default` are broken. The changes in this PR make sense imho.

However, I suggest using the value from `/blog` for all the settings (and allow them to be overridden) like so:

    {% set show_breadcrumbs = header_var('show_breadcrumbs')|defined(header_var('show_breadcrumbs', '/blog'))|defined(true) %}
    {% set show_sidebar = header_var('show_sidebar')|defined(header_var('show_sidebar', '/blog'))|defined(true) %}
    {% set show_pagination = header_var('show_pagination')|defined(header_var('show_pagination', '/blog'))|defined(true) %}

**Comment by tribut** [comment]
The settings where also inconsistently applied when comparing `blog` and `item` pages. I've fixed all of this in #37, which obsoletes this PR.

**Pull request closed without merging**
