### PR TITLE
Remove inline JS and CSS

### PR DESCRIPTION
**Pull request by 9p4**
In order to comply with stricter content-security-policies, move the JS and CSS to their own files. Still WIP

Progress

- [x] Javascript
    - [x] Bricklayer in blog.html.twig
    - [x] Singlepage in modular.html.twig
    - [x] Full testing
- [ ] Inline CSS
    - [ ] Hero partial (background-image)
    - [ ] Checkbox form field
    - [ ] Full testing

### CODE REVIEW

**Comment by NicoHood** [comment]
Which content-security-policies do you refer to?

**Comment by sambhavsaggi** [comment]
For example, in Apache2, we can set `Header set Content-Security-Policy "default-src 'self'; script-src 'self' 'unpkg.com'; img-src *; style-src 'self'"`

This ensures that the only sources of JS and CSS can be loaded from only the main server (self) and the JS can be additionally loaded from unpkg.com. However, this prevents inline style and JS from working unless if you use `unsafe-inline`. It looks like this: `Header set Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; img-src *; style-src 'self' 'unsafe-inline'"`. Using the `unsafe-inline` directive is, as you can tell, unsafe and more or less makes using CSP useless.

**Comment by sambhavsaggi** [comment]
It appears as if the no inline JS is working fine (running on my website). The CSS seems difficult because it contains some Twig.

**Comment by 9p4** [comment]
I don't have time to continue working on this PR. I've forked this theme and am making all of my changes there. https://github.com/9p4/grav-theme-ersei

**Pull request closed without merging**
